# Generated by Django 4.2.15 on 2024-09-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_basket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
